# Site settings
name: Object Pascal Programming
title: Object Pascal Programming
author: Marcos Douglas
email: opp@delfire.net
timezone: America/Sao_Paulo
locale: pt_BR
copyright: "(c) Marcos Douglas, 2016"
encoding: utf-8
description: > # this means to ignore newlines until "baseurl:"
  Sacadas sobre Programação Orientada a Objetos e Object Pascal.
keywords:
  - pascal
  - object pascal
  - delphi
  - freepascal
  - fpc
  - lazarus
  - marcos douglas blog
  - orientação a objetos
  - object oriented
  - oop
  - poo
  - software development blog
  - programming blog
  - quality of software
  - software blog
  - high quality programming
baseurl: ""
url: "http://objectpascalprogramming.com"
date_format: "%b %-d, %Y"
destination: ../site

# Build settings
highlighter: pygments
permalink: /posts/:title/
excerpt_separator: <!--more-->
paginate: 5
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
sass:
  compressed: true
  
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  
# Optional features
animated: true
show_related_posts: true
show_post_footers: true
show_social_icons: true
ajaxify_contact_form: true

# Google services
google_enabled: true
google_analytics: UA-72532239-1
google_verification:

# Disqus post comments
disqus_shortname: objectpascalprogramming
disqus_enabled: true

# Facebook Comments plugin
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: mdbs99
bitbucket_username: mdbs99
stackoverflow_id:
facebook_site: objectpascalprogramming
twitter_username: mdbs99
facebook_username: objectpascalprogramming
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Compartilhe'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true
